# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tech_ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tech_ios

pod 'YYModel', '~> 1.0.4'
pod 'YYWebImage', '~> 1.0.5'
pod 'YTKNetwork', '~> 2.0.3'

pod 'SDWebImage', '~> 3.8.2'

pod 'SDAutoLayout', '~> 2.1.8'

pod 'Masonry', '1.0.2'

pod 'WTPhotoBrowser', '~> 0.0.16'

pod 'BlocksKit', '~> 2.2.5'


pod 'Toast', '~> 3.1.0'
pod 'MBProgressHUD', '~> 0.9.2'

pod 'FMDB', '~> 2.6.2'
pod 'MJRefresh', '~> 3.1.12'

#二维码, 条码 扫描
pod 'LBXScan', '~> 1.1.1'

#滚动菜单栏, 多种样式
#资源地址: https://github.com/tianzhuo112/VTMagic.git
pod 'VTMagic', '~> 1.2.4'

pod 'UITableView+FDTemplateLayoutCell', '~> 1.5.beta'
pod 'TPKeyboardAvoiding', '~> 1.3.1'
pod 'ACEExpandableTextCell', '~> 1.0.4'
pod 'DZNEmptyDataSet', '~> 1.8.1'

pod 'NJKWebViewProgress', '~> 0.2.3'
pod 'JTCalendar', '~> 2.1.9'
pod 'FTPopOverMenu', '~> 1.3.3'

pod 'IQKeyboardManager'
pod 'TZImagePickerController', '1.7.8'   #仿微信图片选择

  target 'tech_iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'tech_iosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
